config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get '/tasks/new', to: 'tasks#new', as: 'new_task'

  get '/tasks', to: 'tasks#index', as: 'tasks'

  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: 'task'

  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'

  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update]

  def index
    # stuff here to display the tasks. NOT in the view I think?
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:notice] = 'You have made a task!'
      redirect_to @task
    else
      render :new
    end
  end

  def set_task
    @task = Task.find(params[:id])
    # @task = Task.find_by(id: params[:id]) Not here?
  end

  def task_params
    params.require(:task).permit(:id, :title, :details, :completed)
  end

  def edit
    # form edit?
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'You edited the task :)'
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = 'DESTROYED'
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with(model: @task, local: true, method: :patch) do |form| %>
  <%= form.label :title, class: "form-control"  %>
  <%= form.text_field :title %>

  <%= form.label :details, class: "form-control"  %>
  <%= form.text_area :details %>

  <%= form.label :completed %>
  <%= form.check_box :completed %>

  <%= form.submit %>
<% end %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/index.html.erb
<div class="card">
<h1>All Tasks</h1>


<% @tasks.each do |task| %>
  <li>
    <%= check_box_tag "task_ids[]", task.id, task.completed %>
    <%= link_to task.title, task_path(task) %>
    <%= form_with(model: task, url: task_path(task), method: :delete, class: 'd-inline') do |form| %>
      <%= form.submit 'Delete', class: 'btn btn-danger btn-sm'%>
    <% end %>
  </li>

<% end %>
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>

</div>

<ul>

app/views/tasks/new.html.erb
<div class="task-form">
<h1>New Task</h1>

<%= form_with(model: @task, local: true) do |form| %>
  <%= form.label :title, class: "" %>
  <%= form.text_field :title, class: "form-control" %>

  <%= form.label :details, class: "" %>
  <%= form.text_area :details, class: "form-control" %>

  <%= form.label :completed%>
  <%= form.check_box :completed%>

  <button type="button" class="text-decoration-none btn btn-dark shadow-lg mt-1"><%= form.submit class: "button1"%></button>
<% end %>

<button type="button" class="text-decoration-none btn btn-dark shadow-lg mt-1"><%= link_to 'Back to Tasks', tasks_path, class: "button2" %></button>

</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><strong>Details:</strong> <%= @task.details %></p>
<p><strong>Completed:</strong> <%= @task.completed ? 'Yes' : 'No' %></p>

<%= link_to 'Edit Task', edit_task_path(@task), class: 'btn btn-primary' %>


<%= link_to 'Back to Tasks', tasks_path %>